services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: dev
    command: ["sh", "-c", "npm i && npm run dev"]
    container_name: ${WEB_CONTAINER_NAME}
    depends_on:
      - cms
    environment:
      - CMS_HOST=${WEB_CMS_HOST}
      - CMS_PORT=${WEB_CMS_PORT}
    networks:
      - frontend
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app

  cms:
    build:
      context: ./cms
      dockerfile: Dockerfile
      target: dev
    command: ["sh" , "-c", "npm i && npm run develop"]
    container_name: ${CMS_CONTAINER_NAME}
    depends_on:
      db:
        condition: service_healthy
    environment:
      - HOST=${CMS_HOST}
      - PORT=${CMS_PORT}
      - APP_KEYS=${CMS_APP_KEYS}
      - API_TOKEN_SALT=${CMS_API_TOKEN_SALT}
      - ADMIN_JWT_SECRET=${CMS_ADMIN_JWT_SECRET}
      - TRANSFER_TOKEN_SALT=${CMS_TRANSFER_TOKEN_SALT}
      - DATABASE_CLIENT=${CMS_DATABASE_CLIENT}
      - DATABASE_HOST=${CMS_DATABASE_HOST}
      - DATABASE_PORT=${CMS_DATABASE_PORT}
      - DATABASE_NAME=${CMS_DATABASE_NAME}
      - DATABASE_USERNAME=${CMS_DATABASE_USERNAME}
      - DATABASE_PASSWORD=${CMS_DATABASE_PASSWORD}
      - DATABASE_SSL=${CMS_DATABASE_SSL}
      - JWT_SECRET=${CMS_JWT_SECRET}

    networks:
      - frontend
      - backend
    ports:
      - "1337:1337"
    volumes:
      - ./cms:/app

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: ${DB_CONTAINER_NAME}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      retries: 3
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

networks:
  frontend:
  backend:
