import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { Header } from "./components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body
          className="antialiased flex flex-col h-screen"
        >
          {/* ヘッダー */}
          <div className="sticky top-0">
            <Header />
          </div>
          {/* メインコンテンツ */}
          <main className="my-8">
            {children}
          </main>
        </body>
      </Providers>
    </html>
  );
}
